services:

  postgres:
    profiles:
      - dev
      - prod
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gtfse'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  gtfse-api:
    profiles:
      - prod
    image: 'ghcr.io/nschaber/gtfse-api:latest'
    ports:
      - '8080'
