services:

  gtfse-postgis:
    profiles:
      - dev
      - prod
    image: docker.io/postgis/postgis:18-3.6-alpine
    build:
      context: https://github.com/postgis/docker-postgis.git#master:18-3.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_ENCODING: UNICODE
      POSTGRES_COLLATE: C
      POSTGRES_COLLATE_TYPE: C
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "gtfse-postgis:/var/lib/postgresql/data:rw"
      - "./config/postgres/scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h gtfse-postgis -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  gtfse-api:
    scale: 2
    profiles:
      - prod
    image: 'ghcr.io/nschaber/gtfse-api:latest'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      VIRTUAL_PATH: "/api"
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: "8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - '8080'

  gtfse-ui:
    profiles:
      - prod
    image: 'ghcr.io/nschaber/gtfse-ui:latest'
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: "3000"
    expose:
      - "3000"

  gtfse-proxy:
    image: nginxproxy/nginx-proxy
    profiles:
      - prod
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:

  gtfse-postgis:
    name: gtfse-postgis